apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  template:
    replicas: 1
    spec:
      containers:
      - name: apache
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
