apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: apache
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
